/**
 * Server-side fetcher for working Altmo Core (Rails) API endpoints.
 * Uses 24h in-memory cache (same pattern as air-quality.ts, traffic-flow.ts).
 * Prefers static JSON files (generated by scripts/refresh-core-data.sh) for
 * instant cold starts; falls back to live Rails API when static data is empty.
 *
 * Response shapes verified 2026-02-14 (post-Apipie fix):
 *   /statistics/overall  → { success, overall_statistics: { people, activitiesCount, distance(m), co2Offset, fuelSaved, moneySaved } }
 *   /geo_markers          → { success, data: { geo_markers: [{ id, associable_type, associable_id, associable_name, lat, lon, layer_type, city_id }] } }
 *   /routes/bulk           → { success, data: { routes: [{ activity_id, activity_type, start_date, distance, path, ... }] } }
 */

import { railsApi } from '$lib/rails-api';
import staticGlobalStats from '$lib/data/global-stats.json';
import staticGeoMarkers from '$lib/data/geo-markers.json';
import staticCompanyGroups from '$lib/data/company-groups.json';

const CACHE_TTL = 24 * 60 * 60 * 1000; // 24 hours

// ── Types ──

export interface GlobalStats {
	activeUsers: number;
	activitiesCount: number;
	distanceKm: number;
	co2Offset: number;
	fuelSaved: number;
	moneySaved: number;
}

export interface GeoMarker {
	id: number;
	name: string;
	lat: number;
	lon: number;
	type: string;
	associableId: number;
	cityId: number | null;
	totalActivities?: number;
	activeUsers?: number;
	totalKm?: number;
	empCount?: number;
}

export interface CompanyGroup {
	id: number;
	name: string;
	cityId: number | null;
	activitiesCount: number;
	usersCount: number;
	totalKm: number;
	facilityCount: number;
}

// ── Cache ──

interface CacheEntry<T> {
	data: T;
	timestamp: number;
}

const statsCache: { entry: CacheEntry<GlobalStats> | null } = { entry: null };

function isFresh<T>(entry: CacheEntry<T> | null | undefined): entry is CacheEntry<T> {
	return !!entry && Date.now() - entry.timestamp < CACHE_TTL;
}

// ── Fetchers ──

/**
 * GET /statistics/overall → global impact totals
 * Tries live Rails API first (with 24h cache), falls back to static JSON.
 */
export async function getGlobalStats(): Promise<GlobalStats | null> {
	if (isFresh(statsCache.entry)) return statsCache.entry.data;

	try {
		const raw = await railsApi<{
			success: boolean;
			overall_statistics: {
				people: number;
				activitiesCount: number;
				distance: number;
				co2Offset: number;
				fuelSaved: number;
				moneySaved: number;
			};
		}>('/statistics/overall');

		const s = raw.overall_statistics;
		const data: GlobalStats = {
			activeUsers: s.people ?? 0,
			activitiesCount: s.activitiesCount ?? 0,
			distanceKm: Math.round((s.distance ?? 0) / 1000),
			co2Offset: Math.round(s.co2Offset ?? 0),
			fuelSaved: Math.round(s.fuelSaved ?? 0),
			moneySaved: Math.round(s.moneySaved ?? 0)
		};

		statsCache.entry = { data, timestamp: Date.now() };
		return data;
	} catch (err) {
		console.error('[altmo-core] Failed to fetch global stats:', err);
		// Fall back to static data if available
		const s = staticGlobalStats as GlobalStats;
		if (s.activitiesCount > 0) {
			console.log('[altmo-core] Using static global stats fallback');
			return s;
		}
		return null;
	}
}

/**
 * Geo markers from static JSON (enriched with activity stats by refresh-core-data-db).
 * Static JSON is the canonical source — it includes totalActivities, activeUsers, etc.
 * that the Rails API does not provide.
 */
export async function getGeoMarkers(): Promise<GeoMarker[] | null> {
	const markers = staticGeoMarkers as unknown as GeoMarker[];
	if (markers.length > 0) return markers;
	return null;
}

/**
 * Company groups from static JSON (parent orgs that aggregate multiple facilities).
 * Used for the leaderboard — groups have pre-aggregated stats from the Rails DB.
 */
export function getCompanyGroups(): CompanyGroup[] {
	return staticCompanyGroups as unknown as CompanyGroup[];
}

