/**
 * Static transit data reader — loads pre-fetched transit JSON from disk.
 * These files are generated by scripts/refresh-transit-data.sh and git-tracked.
 *
 * Used by qol-overrides.ts for instant rail_transit_km computation
 * (no Overpass API calls at request time).
 *
 * The pulse/transit page still uses the live fetchTransitData() for full
 * station/line data with 24h caching — this module is for QoL scoring only.
 */

import type { TransitData } from '$lib/utils/transit';

// Static imports — Vite bundles these into the serverless function
import ahmedabadData from '$lib/data/transit/ahmedabad.json';
import bengaluruData from '$lib/data/transit/bengaluru.json';
import chennaiData from '$lib/data/transit/chennai.json';
import delhiData from '$lib/data/transit/delhi.json';
import hyderabadData from '$lib/data/transit/hyderabad.json';
import indoreData from '$lib/data/transit/indore.json';
import kochiData from '$lib/data/transit/kochi.json';
import mumbaiData from '$lib/data/transit/mumbai.json';
import puneData from '$lib/data/transit/pune.json';

interface StaticTransitData extends TransitData {
	_metrics?: {
		metroKm: number;
		suburbanRailKm: number;
		totalRailKm: number;
	};
}

const STATIC_DATA: Record<string, StaticTransitData> = {
	ahmedabad: ahmedabadData as unknown as StaticTransitData,
	bengaluru: bengaluruData as unknown as StaticTransitData,
	chennai: chennaiData as unknown as StaticTransitData,
	delhi: delhiData as unknown as StaticTransitData,
	hyderabad: hyderabadData as unknown as StaticTransitData,
	indore: indoreData as unknown as StaticTransitData,
	kochi: kochiData as unknown as StaticTransitData,
	mumbai: mumbaiData as unknown as StaticTransitData,
	pune: puneData as unknown as StaticTransitData
};

/**
 * Get pre-computed rail transit km from static data.
 * Returns { totalKm, metroKm, suburbanRailKm } or null if no static data.
 */
export function getStaticRailTransitKm(cityId: string): {
	totalKm: number;
	metroKm: number;
	suburbanRailKm: number;
} | null {
	const data = STATIC_DATA[cityId];
	if (!data?._metrics) return null;

	const { metroKm, suburbanRailKm, totalRailKm } = data._metrics;
	if (totalRailKm === 0 && metroKm === 0 && suburbanRailKm === 0) return null;

	return { totalKm: totalRailKm, metroKm, suburbanRailKm };
}

/**
 * Get full static transit data for a city.
 * Returns the pre-fetched TransitData or null if empty/not available.
 */
export function getStaticTransitData(cityId: string): TransitData | null {
	const data = STATIC_DATA[cityId];
	if (!data) return null;

	// Check if the data has any content (not just empty placeholder)
	const hasContent =
		data.busStops.length > 0 ||
		data.metroStations.length > 0 ||
		data.metroLines.length > 0 ||
		data.railStations.length > 0 ||
		data.railLines.length > 0;

	return hasContent ? data : null;
}

/**
 * Check if static transit data has been populated (not just placeholders).
 */
export function hasStaticTransitData(): boolean {
	return Object.values(STATIC_DATA).some(
		(d) => d.busStops.length > 0 || d.metroStations.length > 0 || d.railStations.length > 0
	);
}
